<?php
/**
 * @file
 * Install file for the feature.
 */

/**
 * Implements hook_enable().
 *
 * During tests we are doing whatever we want with entities
 * packed in feature - so it is reasonable to reset any
 * cached changes each time.
 */
function entity_feature_enable() {
  // Reset all static variables.
  drupal_static_reset();
  // Perform rebuilds and flush remaining caches.
  drupal_flush_all_caches();
}
